### PR TITLE
Bump version to 0.3.1

### PR DESCRIPTION
**Pull request by nehaljwani**
- Switch from wheel to source tarball
- Update about section

To be merged after https://github.com/conda-forge/staged-recipes/pull/3668

### CODE REVIEW

**Comment by takluyver** [comment]
As you're adding yourself to the maintainers list (which gives you the technical ability to update the package yourself without a pull request): who are you? I'm absolutely happy to add another maintainer if you're interested in the package, but it implies a certain amount of trust, and I don't know anything about you yet. 🙂

**Comment by nehaljwani** [comment]
There is no reason for you to trust me... yet. I am just another computer programmer who happens to work closely with the Anaconda Distribution team.  As for this package, yes, I am interested in it, interested enough to send a PR for a feature request https://github.com/jupyter/testpath/pull/10 :slightly_smiling_face:

**Comment by takluyver** [comment]
Thanks :-) That PR went well - once I've seen your name around a few more times, I'll probably be happy to add you to the maintainers list.

I'm just waiting for the tests to finish on Appveyor now, then I think this should be ready to go.

**Comment by ocefpaf** [comment]
@takluyver's request is quite reasonable. Unfortunately due to conda-forge's many compartments  someone can be a veteran for some and a new face for others.

Maybe it is best to split the PR into the update and the addition of @nehaljwani to the team. That way the vetting of the new member can take its time while the update, which is kind of part of the vetting process, can be quickly merged.

What do you think?

**Comment by nehaljwani** [comment]
I am in no hurry to be added as a maintainer. I have already removed myself from the patch. Although I'll still make PRs for new versions :)

**Comment by nehaljwani** [comment]
Finally, the AppVeyor build has finished!

**Comment by takluyver** [comment]
Thanks for letting me know;  I wouldn't have looked until tomorrow otherwise.

**Pull request merged**
